---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: consul-1
  annotations:
    volume.beta.kubernetes.io/storage-class: default
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 50Gi
